#pragma once

#ifdef __cplusplus
extern "C" {
#endif

int addi32_carry(int, int, int *);

__int64 addi64(__int64, __int64);
__int64 subi64(__int64, __int64);
__int64 muli64(__int64, __int64);

void addi64p(__int64, __int64, __int64 *);
void subi64p(__int64, __int64, __int64 *);
void muli64p(__int64, __int64, __int64 *);

#if defined(BIGINT_ENABLE_MSVC_32_OPTIMIZATION)

/* The following optimized assembly routines are generated by Claude AI
  I am not an assembly expert, and I do not write assembly code/s.
  So I asked an AI to write some for me. Hopefully you understood it.
  Actually it is still slow, but in fact I would not write my own
  assembly code, I'll just use the built in intrinsic functions that
  the compiler supports and provides, but unfortunately, some compiler
  does not support or does not have it, so I am stuck to use some bunch
  of assembly code/s. Thank you!
*/

int addi32_carry(int a, int b, int *result) {
  int carry;
  __asm {
    mov  eax, dword ptr [a]
    add  eax, dword ptr [b]      ; add, sets CF on unsigned carry-out
    mov  edx, dword ptr [result]
    mov  dword ptr [edx], eax    ; store sum through pointer
    setc al                      ; al = 1 if CF set, else 0
    movzx eax, al                ; zero-extend to full 32-bit int
    mov  carry, eax
  }
  return carry;
}

__int64 addi64(__int64 a, __int64 b) {
  __int64 result;
  __asm {
    mov  eax, dword ptr [a]      ; low 32 bits of a
    mov  edx, dword ptr [a+4]    ; high 32 bits of a
    add  eax, dword ptr [b]      ; add low 32 bits, sets carry flag
    adc  edx, dword ptr [b+4]    ; add high 32 bits + carry
    mov  dword ptr [result],   eax
    mov  dword ptr [result+4], edx
  }
  return result;
}

__int64 subi64(__int64 a, __int64 b) {
  __int64 result;
  __asm {
    mov  eax, dword ptr [a]      ; low 32 bits of a
    mov  edx, dword ptr [a+4]    ; high 32 bits of a
    sub  eax, dword ptr [b]      ; subtract low 32 bits, sets borrow (carry) flag
    sbb  edx, dword ptr [b+4]    ; subtract high 32 bits - borrow
    mov  dword ptr [result],   eax
    mov  dword ptr [result+4], edx
  }
  return result;
}

__int64 muli64(__int64 a, __int64 b) {
  __int64 result;
  __asm {
    push ebx                     ; preserve ebx (MSVC requires this)

    mov  eax, dword ptr [a+4]    ; a_hi
    mov  ecx, dword ptr [b]      ; b_lo
    mul  ecx                     ; edx:eax = a_hi * b_lo (unsigned 32x32->64)
    mov  ebx, eax                ; keep low 32 bits -> contributes to high word

    mov  eax, dword ptr [a]      ; a_lo
    mov  ecx, dword ptr [b+4]    ; b_hi
    mul  ecx                     ; edx:eax = a_lo * b_hi
    add  ebx, eax                ; accumulate into high-word contribution

    mov  eax, dword ptr [a]      ; a_lo
    mul  dword ptr [b]           ; edx:eax = a_lo * b_lo (full 64-bit unsigned product)
    add  edx, ebx                ; fold in the two cross terms

    mov  dword ptr [result],   eax
    mov  dword ptr [result+4], edx

    pop  ebx                     ; restore ebx
  }
  return result;
}

void addi64p(__int64 a, __int64 b, __int64 *result) {
  __asm {
    push edi
    mov  edi, result              ; edi = pointer to result

    mov  eax, dword ptr [a]
    mov  edx, dword ptr [a+4]
    add  eax, dword ptr [b]
    adc  edx, dword ptr [b+4]

    mov  dword ptr [edi],   eax
    mov  dword ptr [edi+4], edx

    pop  edi
  }
}

void subi64p(__int64 a, __int64 b, __int64 *result) {
  __asm {
    push edi
    mov  edi, result

    mov  eax, dword ptr [a]
    mov  edx, dword ptr [a+4]
    sub  eax, dword ptr [b]
    sbb  edx, dword ptr [b+4]

    mov  dword ptr [edi],   eax
    mov  dword ptr [edi+4], edx

    pop  edi
  }
}

void muli64p(__int64 a, __int64 b, __int64 *result) {
  __asm {
    push ebx
    push edi
    mov  edi, result              ; edi = pointer to result

    mov  eax, dword ptr [a+4]     ; a_hi
    mov  ecx, dword ptr [b]       ; b_lo
    mul  ecx                      ; edx:eax = a_hi * b_lo
    mov  ebx, eax                 ; keep low 32 bits

    mov  eax, dword ptr [a]       ; a_lo
    mov  ecx, dword ptr [b+4]     ; b_hi
    mul  ecx                      ; edx:eax = a_lo * b_hi
    add  ebx, eax                 ; accumulate cross terms

    mov  eax, dword ptr [a]       ; a_lo
    mul  dword ptr [b]            ; edx:eax = a_lo * b_lo
    add  edx, ebx                 ; fold cross terms into high word

    mov  dword ptr [edi],   eax
    mov  dword ptr [edi+4], edx

    pop  edi
    pop  ebx
  }
}

#endif

#ifdef __cplusplus
}
#endif