name: Multiprecision Big Integer Library Windows Test CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Meson
        run: pip install meson

      - name: Install Ninja
        run: pip install ninja

      - name: Prepare
        run: meson setup build

      - name: Compile
        run: ninja -C build

      - name: Run
        run: .\build\multiprecisionArithmetic\bigIntTest.exe